=== dorivalq/sap-pi-mapping/sap-jco-connect/events_v2_entrada.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	elementFormDefault="qualified">
	<xs:element name="event">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="meterid" type="xs:string" />
				<xs:element name="sdp" type="xs:string" />
				<xs:element name="message" type="xs:string" />
				<xs:element name="logbookid" type="xs:int" minOccurs="0" />
				<xs:element name="startdatetime" type="xs:dateTime" />
				<xs:element name="enddatetime" type="xs:dateTime"
					minOccurs="0" />
				<xs:element name="datetime" type="xs:dateTime" />
				yyyy-MM-dd'T'HH:mm:ss
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== dorivalq/sap-pi-mapping/sap-jco-connect/events_v2_entrada.xml
<?xml version="1.0" encoding="UTF-8"?>
<event xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="events_v2_entrada.xsd">
  <meterid>meterid</meterid>
  <sdp>sdp</sdp>
  <message>message</message>
  <logbookid>0</logbookid>
  <startdatetime>2001-12-31T12:00:00</startdatetime>
  <enddatetime>2001-12-31T12:00:00</enddatetime>
  <datetime>2001-12-31T12:00:00</datetime>
</event>
